mystruct.c File Reference
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include `mystruct.h`
Functions
struct Employee * makerndEmployee ()
char * rndstr (size_t length)
int rndint (int MIN, int MAX)
struct Employee * makeEmployee (int birth, int start, const char *name)
void printEmployee (struct Employee *e)
struct Employee ** makeRandomArray (size_t n)
void printAllEmployee (struct Employee **arr, size_t n)
struct Employee ** makeShallowCopy (struct Employee **arr, size_t n)
void destructArray (struct Employee **arr, size_t n)
struct Employee ** makeDeepCopy (struct Employee **arr, size_t n)
Function Documentation
destructArray()
void destructArray (struct Employee ** arr, size_t n)
Frees the given array from memory
Parameters
arr,the array to free
n,the size of the array
Referenced by testDeallocate().
makeDeepCopy()
struct Employee** makeDeepCopy (struct Employee ** arr, size_t n)
Makes a deep copy of the given array
Parameters
arr,the array to copy
n,the size of the array
Returns
a deep copy with all new pointers and adresses!!
References Employee::birth_year, makeEmployee(), Employee::name, and Employee::start_year.
Referenced by testDeepCopy().
makeEmployee()
struct Employee* makeEmployee (int birth, int start, const char * name)
Allocates an Employee struct and fills in its fields
Parameters
birth Year the employee was born.
start Year the employee started with the company.
name String containing employee's name
Returns
Pointer to Employee struct, newly allocated from the heap.
References Employee::birth_year, Employee::name, and Employee::start_year.
Referenced by makeDeepCopy(), makerndEmployee(), and testMakeEmployee().
makeRandomArray()
struct Employee** makeRandomArray (size_t n)
Creates and array of pointers to random Employee
Parameters
n,the size of the array to be made
Returns
a pointer to the created array
References makerndEmployee().
Referenced by testDeallocate(), testDeepCopy(), testMakeRndAndPrint(), and testShallowCopy().
makerndEmployee()
struct Employee* makerndEmployee ()
mystruct.c
Author
Mike Ciaraldi Creates an employ with random values between 1919 and 2019 and a random string of length 3 - 20
Returns
the pointer to the above Employee
References makeEmployee(), rndint(), and rndstr().
Referenced by makeRandomArray().
makeShallowCopy()
struct Employee** makeShallowCopy (struct Employee ** arr, size_t n)
Creates a new array that is a shallow copy
Parameters
arr,the array to create the copy of
n,length of the array
Returns
a pointer to the new array
Referenced by testShallowCopy().
printAllEmployee()
void printAllEmployee (struct Employee ** arr, size_t n)
Prints all Employee in the given array
Parameters
arr,the array to print
n,the size of the array to print
References printEmployee().
Referenced by testDeepCopy(), testMakeRndAndPrint(), and testShallowCopy().
printEmployee()
void printEmployee (struct Employee * e)
Prints the given Employee in the following format `Requested Employee is [name], born [birth_year], started working [start_year]`
Parameters
e,a pointer to the Employee to print
References Employee::birth_year, Employee::name, and Employee::start_year.
Referenced by printAllEmployee(), testMakeEmployee(), and testPrintEmployee().
rndint()
int rndint (int MIN, int MAX)
Creates a random integer between MIN and MAX
Parameters
MIN (Inclusive)
MAX (Exclusive)
Returns
a random Integer
Referenced by makerndEmployee().
rndstr()
char* rndstr (size_t length)
Creates a random string made of letters a - z starting with an upper case letter A - Z
Parameters
length,the size of the string to be created
Returns
the created string
Referenced by makerndEmployee().