tests.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdbool.h>
#include `tests.h`
#include `production.h`
#include `mystruct.h`
Functions
bool tests (void)
bool testPrintEmployee ()
bool testMakeEmployee ()
bool testMakeRndAndPrint ()
bool testShallowCopy ()
bool testDeallocate ()
bool testDeepCopy ()
Function Documentation
testDeallocate()
bool testDeallocate ()
Test the destructArray function, it is either pass or error.
Returns
true
References destructArray(), and makeRandomArray().
Referenced by tests().
testDeepCopy()
bool testDeepCopy ()
Test the makeDeepCopy fuction
Returns
true. The only way to tell if it succeeds is to look at the output
References makeDeepCopy(), makeRandomArray(), and printAllEmployee().
Referenced by tests().
testMakeEmployee()
bool testMakeEmployee ()
Test the make Employee() function by making an employee with known data and printing it.
Returns
true. The only way to tell if it succeeds is to look at the output.
References makeEmployee(), and printEmployee().
Referenced by tests().
testMakeRndAndPrint()
bool testMakeRndAndPrint ()
Test the makeRndEmployee and printEmployee functions
Returns
true. The only way to tell if it succeeds is to look at the output
References makeRandomArray(), and printAllEmployee().
Referenced by tests().
testPrintEmployee()
bool testPrintEmployee (void)
Test the printEmployee() function by creating a known struct and printing it.
Returns
true. The only way to tell if it succeeds is to look at the output.
References Employee::birth_year, MAX_NAME, Employee::name, printEmployee(), and Employee::start_year.
Referenced by tests().
tests()
bool tests (void)
Used to test the functionality of this code
Returns
true if the program ran as intended
References testDeallocate(), testDeepCopy(), testMakeEmployee(), testMakeRndAndPrint(), testPrintEmployee(), and testShallowCopy().
Referenced by main().
testShallowCopy()
bool testShallowCopy ()
Test the makeShallowCopy function
Returns
true. The only way to tell if it succeeds is to look at the output
References makeRandomArray(), makeShallowCopy(), and printAllEmployee().
Referenced by tests().