AntsAndDoodles.cpp File Reference
#include <iostream>
#include `Tests2.h`
#include `Production.h`
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
main function
Parameters
int argc, the amount of arguments passed in the command line
char* argv[], the arguments passed in the command line. gridsize, #doodlebugs, #ants #time_steps seed pause
References Tests2::doTests(), Production::Production(), Production::runProduction(), and Production::~Production().