Tests2 Class Reference
#include <Tests2.h>
Public Member Functions
 Tests2 ()
bool doTests ()
bool gridTest ()
bool makeOrganismTest ()
bool antsMoveTest ()
bool antsBreedTest ()
bool antsDieFromDoodleEatTest ()
bool doodleMoveTest ()
bool doodleBreedTest ()
bool doodleDietest ()
virtual ~Tests2 ()
Constructor & Destructor Documentation
Tests2()
Tests2::Tests2 ()
Basic Tests2 constructor Receives and outputs nothing
~Tests2()
Tests2::~Tests2 () [virtual]
Destructer Receives and outputs nothing
Member Function Documentation
antsBreedTest()
bool Tests2::antsBreedTest ()
Tests to make sure the ANT breed function is working properly
Returns
bool, whether the function runs as expected
References ant, Ant::breed(), Grid::getCellOccupant(), Ant::move(), Ant::setPos(), and Grid::~Grid().
Referenced by doTests().
antsDieFromDoodleEatTest()
bool Tests2::antsDieFromDoodleEatTest ()
Tests to make sure the ANT die function is working properly
Returns
bool, whether the function runs as expected
References doodlebug, Doodlebug::eat(), Grid::getCellOccupant(), Doodlebug::setPos(), Ant::setPos(), and Grid::~Grid().
Referenced by doTests().
antsMoveTest()
bool Tests2::antsMoveTest ()
Tests to make sure the ANT move function is working properly
Returns
bool, whether the function runs as expected
References empty, Grid::getCellOccupant(), Ant::move(), Ant::setPos(), and Grid::~Grid().
Referenced by doTests().
doodleBreedTest()
bool Tests2::doodleBreedTest ()
Tests to make sure the Doodle breed function is working properly
Returns
bool, whether the function runs as expected
References Doodlebug::breed(), doodlebug, Doodlebug::eat(), Grid::getCellOccupant(), Doodlebug::move(), Doodlebug::setPos(), and Grid::~Grid().
Referenced by doTests().
doodleDietest()
bool Tests2::doodleDietest ()
Tests to make sure the Doodle die function is working properly
Returns
bool, whether the function runs as expected
References Doodlebug::die(), doodlebug, Doodlebug::eat(), Grid::getCellOccupant(), Doodlebug::move(), Doodlebug::setPos(), and Grid::~Grid().
Referenced by doTests().
doodleMoveTest()
bool Tests2::doodleMoveTest ()
Tests to make sure the Doodle move function is working properly
Returns
bool, whether the function runs as expected
References empty, Grid::getCellOccupant(), Doodlebug::move(), Doodlebug::setPos(), and Grid::~Grid().
Referenced by doTests().
doTests()
bool Tests2::doTests ()
Tests the program
Returns
bool, whether the function ran as expected
References antsBreedTest(), antsDieFromDoodleEatTest(), antsMoveTest(), doodleBreedTest(), doodleDietest(), doodleMoveTest(), gridTest(), and makeOrganismTest().
Referenced by main().
gridTest()
bool Tests2::gridTest ()
Tests to make sure the Grid object is working properly
Returns
bool, whether the function runs as expected
References ant, empty, Grid::getCellOccupant(), Grid::setCellOccupant(), and Grid::~Grid().
Referenced by doTests().
makeOrganismTest()
bool Tests2::makeOrganismTest ()
Tests to make sure the ANT and DOODLEBUG initializers are working properly
Returns
bool, whether the function runs as expected
References doodlebug, empty, Grid::getCellOccupant(), Doodlebug::setPos(), Ant::setPos(), and Grid::~Grid().
Referenced by doTests().
The documentation for this class was generated from the following files:
 Tests2.h
 Tests2.cpp