Ant Class Reference
#include <Ant.h>
Public Member Functions
 Ant ()
 Ant (int r, int c)
void setPos (int r, int c, Grid *grid)
bool move (Grid *grid)
bool breed (Grid *grid)
 ~Ant ()
Private Attributes
int row = 0
int col = 0
int movesteps = 0
Additional Inherited Members
Constructor & Destructor Documentation
Ant() [1/2]
Ant::Ant ()
This is the default constructor It has no parameters and returns nothing
Referenced by breed().
Ant() [2/2]
Ant::Ant (int r, int c)
Constructor of the ANT class
Parameters
r,the staring x position
c,the starting y position
References col, and row.
~Ant()
Ant::~Ant ()
Destructer Receives and outputs nothing
Member Function Documentation
breed()
bool Ant::breed (Grid * grid)
References ant, Ant(), col, empty, Grid::findAdjWithStatus(), movesteps, row, Grid::setCellOccupant(), and setPos().
Referenced by Tests2::antsBreedTest(), and Production::runProduction().
move()
bool Ant::move (Grid * grid)
References ant, col, empty, Grid::findAdjWithStatus(), movesteps, Grid::removeCellOccupant(), row, Grid::setCellOccupant(), and Organism::visited.
Referenced by Tests2::antsBreedTest(), Tests2::antsMoveTest(), and Production::runProduction().
setPos()
void Ant::setPos (int r, int c, Grid * grid)
This sets the x and y position of the object
Parameters
int r, y position
int c, x position
References ant, col, row, and Grid::setCellOccupant().
Referenced by Tests2::antsBreedTest(), Tests2::antsDieFromDoodleEatTest(), Tests2::antsMoveTest(), breed(), Tests2::makeOrganismTest(), and Production::runProduction().
Field Documentation
col
int Ant::col = 0 [private]
Referenced by Ant(), breed(), move(), and setPos().
movesteps
int Ant::movesteps = 0 [private]
Referenced by breed(), and move().
row
int Ant::row = 0 [private]
Referenced by Ant(), breed(), move(), and setPos().
The documentation for this class was generated from the following files:
 Ant.h
 Ant.cpp