Cell Class Reference
#include <Cell.h>
Public Member Functions
 Cell ()
 Cell (Organism *ptr)
bool setOccupant (occupationStatus g, Organism *ptr)
 occupationStatus getOccupant ()
 Organism * getOrg ()
virtual ~Cell ()
Private Attributes
 Organism * org
 occupationStatus guest
Constructor & Destructor Documentation
Cell() [1/2]
Cell::Cell ()
This is the default constructor
Returns
an empty cell object
References empty, guest, and org.
Cell() [2/2]
Cell::Cell (Organism * ptr)
References ant, doodlebug, guest, Organism::isPrey(), and org.
~Cell()
Cell::~Cell () [virtual]
Destructer Receives and outputs nothing
References org.
Referenced by Grid::~Grid().
Member Function Documentation
getOccupant()
 occupationStatus Cell::getOccupant ()
References guest.
Referenced by Grid::getCellOccupant(), and Grid::printGrid().
getOrg()
 Organism * Cell::getOrg ()
References org.
Referenced by Grid::getCellPointer().
setOccupant()
bool Cell::setOccupant (occupationStatus g, Organism * ptr)
References guest, and org.
Referenced by Grid::removeCellOccupant(), and Grid::setCellOccupant().
Field Documentation
guest
 occupationStatus Cell::guest [private]
Referenced by Cell(), getOccupant(), and setOccupant().
org
 Organism* Cell::org [private]
Referenced by Cell(), getOrg(), setOccupant(), and ~Cell().
The documentation for this class was generated from the following files:
 Cell.h
 Cell.cpp