production.h File Reference
#include <stdio.h>
Functions
bool production (int argc, char *argv[])
void PlayOne (unsigned int nr, unsigned int nc, char *Old, char *New)
void usage (void)
char getLetter (int row, int col, int nCols, char *Old)
int HowManyNeighbors (int row, int col, int nRows, int nCols, char *Old)
void readFileIntoArray (int nRows, int nCols, int howManyLinesInFile, int maximumWidth, char *ar_p, FILE *fp)
int generate (int gens, int nRows, int nCols, char *old_p, char *new_p, char *other_p, char print, char pause)
bool anyX (char *arr, int nRows, int nCols)
bool sameContent (char *one_p, char *another_p, int nRows, int nCols)
void printThis (int nRows, int nCols, char *old_p)
void swapPntr (char **other_pl, char **old_p, char **new_p)
Function Documentation
anyX()
bool anyX (char * arr, int nRows, int nCols)
anyX is a helper function to find out if the array has any X chars
Parameters
int nRows, the number of rows in the game
int nCols, the number of columns in the game
char* arr, the pointer to the target array
Returns
True if the array contains 'x' False if not
Referenced by generate().
generate()
int generate (int gens, int nRows, int nCols, char * old_p, char * new_p, char * other_p, char print, char pause)
generate runs the game for the designated amount of rounds and checks if the game should end
Parameters
int gens, the number rounds the game will try and run for
int nRows, the number of rows in the game
int nCols, the number of columns in the game
char* old_p, the pointer to the old array
char* new_p, the pointer to the new array
char* other_p, the pointer to the third array
char print, character to decide if the game should print after each generation ('y' for yes, 'n' for no)
char pause, character to decide of the game should pause after each generation ('y' for yes, 'n' for no)
Returns
the number of rounds the game ran
References anyX(), PlayOne(), printThis(), sameContent(), and swapPntr().
Referenced by production().
getLetter()
char getLetter (int row, int col, int nCols, char * Old)
getLetter gets the char at the given position in the given array
Parameters
int row, row of desired char
int col, column of desired char
int nCols, the number of columns in the game
char* Old, the array to get the character from
Returns
the char at the given position in the given array
Referenced by HowManyNeighbors(), PlayOne(), printThis(), and sameContent().
HowManyNeighbors()
int HowManyNeighbors (int row, int col, int nRows, int nCols, char * Old)
HowManyNeighbors is a helper function to find out how many Xs are adjecent
Parameters
int row, row of desired char
int col, column of desired char
int nRows, the number of rows in the game
int nCols, the number of columns in the game
char* Old, the array to compare the character from
Returns
the number of Xs that are next to the given position in any cardinal direction
References getLetter().
Referenced by PlayOne().
PlayOne()
void PlayOne (unsigned int nr, unsigned int nc, char * Old, char * New)
PlayOne carries out one generation
Parameters
unsigned int nr, the number of rows in the petri dish
unsigned int nc, the number of columns in the petri dish
char* Old, the location of the upper left of starting petri dish
char* New, the location of the upper left of the ending petri dish
Returns
There is none, because results are in New array
References getLetter(), and HowManyNeighbors().
Referenced by generate(), and testPlayOne().
printThis()
void printThis (int nRows, int nCols, char * old_p)
printThis prints an array
Parameters
int nRows, the number of rows in the game
int nCols, the number of columns in the game
char* old_p, the pointer to the target array
References getLetter().
Referenced by generate(), and readFileIntoArray().
production()
bool production (int argc, char * argv[])
Production begins the program and initializes the generations
Parameters
int argc, the number of arguments in the command line call. Must be greater than 5.
char* argv[], the array of the passed arguments in the command line call
Returns
True if production completed, False if otherwise
References generate(), readFileIntoArray(), and usage().
Referenced by main().
readFileIntoArray()
void readFileIntoArray (int nRows, int nCols, int howManyLinesInFile, int maximumWidth, char * ar_p, FILE * fp)
readFileIntoArray turns the file into an array
Parameters
int nRows, the number of rows in the game
int nCols, the number of columns in the game
int howManyLinesInFile, the number of lines in the original file
int maximumWidth, the number of characters long the original file
char* ar_p, the array to put the characters from the file into
FILE* fp, the file designated as the starting game board
References printThis().
Referenced by production().
sameContent()
bool sameContent (char * one_p, char * another_p, int nRows, int nCols)
sameContent is a helper function that compares two arrays
Parameters
int nRows, the number of rows in the game
int nCols, the number of columns in the game
char* one_p, the pointer to the first target array
char* another_p, the pointer to the second target array
Returns
True if the arrays are identical, False if otherwise
References getLetter().
Referenced by generate().
swapPntr()
void swapPntr (char ** other_p, char ** old_p, char ** new_p)
swapPntr plays musical chairs with the pointers to continue the game and swap the arrays A, B and C
Parameters
char** other_p, the pointer to the array pointer controlling the game
char** old_p, the pointer to the array pointer controlling the game
char** new_p, the pointer to the array pointer controlling the game
Referenced by generate().
usage()
void usage (void)
Referenced by production().